# Generated by Django 3.2.4 on 2021-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='desktop wallpaper.jpg', null=True, upload_to='images'),
        ),
    ]
