# Generated by Django 3.2.6 on 2021-10-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='thumbnail',
            field=models.ImageField(blank=True, default='desktop wallpaper.jpg', null=True, upload_to='images'),
        ),
    ]
