# Generated by Django 3.2.6 on 2021-10-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
    ]
