# Generated by Django 3.2.4 on 2022-01-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
